### ISSUE TITLE
sfg_MULTIPOLYGON

### ISSUE THREAD

**Issue by dcooley** [dcooley/sfheaders#11]
- [x] line_id & polygon_id consolidated into SEXP id_cols in R API, then expanded in C++
- [x] return a list of lists

If polygon_id supplied & not line_id - fine; every polygon is just the outer ring
if line_id supplied and not polygon_id - fine; the multipolygon is just one polygon, made from many lines
if line_id AND polygon_id - the multipolygon is made of many polygons, which are made of many lines

At the C++ level
-

**Comment by mdsumner** [comment]
Is polygon_id and line_id mixed up? 

``` r

library(sfheaders) ## @ eff505cf
df <- structure(list(x = c(0, 1, 3, 2, 1, 0, 1, 1, 2, 1, 3, 4, 4, 3, 
                         3, 3.3, 3.3, 3.8, 3.8, 3.3, 3, 4, 4, 3), 
                     y = c(0, 0, 2, 4, 4, 0, 1, 2, 2, 1, 0, 0, 1, 1, 
                           0, 0.3, 0.8, 0.8, 0.3, 0.3, 3, 2, 3, 3), 
                     polygon_id = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
                                    2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L), 
                     linestring_id = c(3L, 3L, 3L, 3L, 3L, 3L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 5L, 5L, 
                                       5L, 5L, 5L, 4L, 4L, 4L, 4L)), class = c("tbl_df", "tbl", "data.frame"), 
                row.names = c(NA, -24L))

g <- sfg_multipolygon(df, x= "x", y = "y", polygon_id = "polygon_id", linestring_id = "linestring_id")

library(sf)
#> Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0
plot(g, col = "grey")
```

![](https://i.imgur.com/l10v7xj.png)

``` r
g1 <- sfg_multipolygon(df, x= "x", y = "y", polygon_id = "linestring_id", linestring_id = "polygon_id")
plot(g1, col = "grey")
```

![](https://i.imgur.com/SM5P8wN.png)

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dcooley** [comment]
thanks; now fixed.

**Comment by mdsumner** [comment]
Brilliant, thanks!  And confirmed (in record time :)
