### ISSUE TITLE
sf_* to keep properties

### ISSUE THREAD

**Issue by SymbolixAU** [dcooley/sfheaders#41]
similar to `sf_to_df(x, fill = TRUE)`, we could have a `sf_point(x, ..., keep = TRUE)` argument to keep all the attributes. 

We would have to make an assumption that all the attributes are the same for every row of data in the same geometry.

**Comment by dcooley** [comment]
TODO

- [ ] sf_point
- [ ] sf_multipoint
- [ ] sf_linestring
- [ ] sf_multilinestring
- [ ] sf_polygon
- [ ] sf_multipolygon
- [ ] this crash

```
df <- data.frame(
  ml_id = c(1,1,1,1,1,1,1,1,2,2,2,2,2)
  , l_id = c(1,1,1,2,2,3,3,3,1,1,1,2,2)
  , x = rnorm(13)
  , y = rnorm(13)
  , z = rnorm(13)
  , m = rnorm(13)
)

sf_multilinestring( obj = df, x = 2, y = 3, z = 4, m = 5, keep = T, multilinestring_id = 1, linestring_id = 2)
```

**Comment by SymbolixAU** [comment]
I think [this](https://github.com/dcooley/sfheaders/issues/42) is / was causing the crashes.
