### ISSUE TITLE
simpler creator functions?

### ISSUE THREAD

**Issue by mdsumner** [dcooley/sfheaders#63]
Would you consider including these helpers? I wrote them to flesh out #62 before I ran into local problems. I'm using sfheaders so much now that I'd like to rely on them, it's just expected that you input a data frame that contains the relevant columns. (I don't really care about the names of them, but "std_thing" seemed sensible ;)

[WIP at fork, in branch simple-creators-63](https://github.com/mdsumner/sfheaders/tree/simple-creators-63):

- [x] handle `keep` argument  (default to FALSE, same as main funs)
- [x] handle `close` argument (default to FALSE, different to main funs)
- [x] handle `z` and or `m` (include them if those names are present in the input df)
- [x] document as helper funs
- [x] resolve naming, `sf_pt(), sf_mpt(), sf_line(), sf_mline(), sf_poly(), sf_mpoly()`
- [x] tests
- [ ] document example workflows and rationale in vignette
- [x] test on recent R/roxygen (specific to mdsumner's setup atm)
- [x] sf_mpt() is keeping 'multipoint_id' (correctly) ~(and doubling it if keep = TRUE)~

Then the `sf_to_df` output becomes some kind of standard that we can easily round-trip in (usually) internal code (something I was going for with [spbabel](https://github.com/mdsumner/spbabel) with mixed and now deprecated success). 

```R
std_mpoly <- function(x, ...) {
  sfheaders::sf_multipolygon(x, 
                             x = "x", y = "y",
                             linestring_id = "linestring_id", 
                             polygon_id = "polygon_id", 
                             multipolygon_id = "multipolygon_id")
}
std_poly <- function(x, ...) {
  sfheaders::sf_polygon(x, 
                             x = "x", y = "y",
                             linestring_id = "linestring_id", 
                             polygon_id = "polygon_id")
}
std_mline <- function(x, ...) {
  sfheaders::sf_multilinestring(x, 
                        x = "x", y = "y",
                        linestring_id = "linestring_id", 
                        multilinestring_id = "multilinestring_id")
}
std_line <- function(x, ...) {
  sfheaders::sf_linestring(x, 
                                x = "x", y = "y",
                                linestring_id = "linestring_id")
}
std_mpoint <- function(x, ...) {
  sfheaders::sf_multipoint(x, 
                           x = "x", y = "y",
                           point_id = "point_id",
                           multipoint_id = "multipoint_id")
}
std_point <- function(x, ...) {
  sfheaders::sf_point(x, 
                           x = "x", y = "y",
                           point_id = "point_id")
}
```

**Comment by dcooley** [comment]
in principle I'm ok with this. 
What is `std` short for here? I'm wondering if there's not another prefix which doesn't have other obvious* connotations.

*obvious depending on where you're from, of course.

**Comment by mdsumner** [comment]
Oh "standard" - the df names are standard (for this type). It's not great, just what I called it ...

**Comment by mdsumner** [comment]
I suppose `sf_mpoly`, `sf_poly` etc is ok - they are shortened helpers for casual (or internal) use, a bit more informal than the core funs?

**Comment by dcooley** [comment]
I had a similar thought, but there'll be a conflict with `sf_point`

**Comment by mdsumner** [comment]
oh gee ...  `sf_pt`, `sf_mpt` ... - no rush there, I'll flesh out a PR and think some more. Thanks!

**Comment by dcooley** [comment]
yeah names can come later :)

**Comment by dcooley** [comment]
Also, I don't have a style or contribution guide so I'm not too fussy about that, but I've been using `obj` as the object argument because `x` would usually refer to a coordinate column.

**Comment by mdsumner** [comment]
Here's the current set of rules for my helpers, if and when you can review (no rush but in case we catch some early gotchas, I've encountered a few lessons while fleshing this out): 

https://github.com/mdsumner/sfheaders/blob/simple-creators-63/R/sf-helpers.R#L22-L40

I only just realized that `sf_pt()` adds very little as a helper (no '_id' columns needed by `sf_point`, but `sf_pt` *requires* a column-based object that must have column name) - I think this is a good point of difference.

**Comment by dcooley** [comment]
I've merged this into master. 

> document example workflows and rationale in vignette

Happy for you to add to `vignettes/examples.Rmd` if you so wish. I'm not toooo fussed about it though.

**Comment by mdsumner** [comment]
Sweet, thanks! Re vignette, will see how I go - after my current ~obsession~ focus I will cycle back around to this for silicate -> sf helpers so I've put it off a bit. Will close this

**Comment by SymbolixAU** [comment]
Bringing this up as I just thought about it.

If one uses `sf_to_df()` on an `sf` object to create a data.frame, but the `x` column already exists, the actual x coordinate column will be named `x..1`. This will be incorrect if you then call `sf_line()`, for example

```r
library(sf)

sf <- mapdeck::roads
sf$x <- rnorm(nrow(sf))
df <- sfheaders::sf_to_df( sf, fill = TRUE )

## this is wrong, because it usees the `x` column of the data, not the geometry
sfheaders::sf_line(
  obj = df
)
```

I'm aware of the caveats in the documentation which states it expects the columns to be named correctly, but will this example likely break a workflow you had in mind?

**Comment by mdsumner** [comment]
Hmmm, good point - I'm very much for a "no fill" kind of workflow, but this is pretty much why silicate uses 'x_', 'y_' etc. At the time (years ago when Hadley discovered df-nesting) it seemed like a kind of emerging standard to name "internal" stuff that way. It's no guarantee of course, but definitely worth considering. 

I'm thinking about the impact on sfheaders if you were to make obscurer "x" and "y" column names from `sf_to_df()` - would you consider that? My other fallback is "don't use `fill` for pure automation", so I'm happy if they don't change. It's also a style I've become used to, "don't get in the way with users - check and warn, no error if not fatal ..." - you figure out pretty quickly if it's "wrong" when you use the result, as long as you aren't blocked by stern software. ;)

So, long story: I'm not bothered, but def deserves doc, and warnings for these typical obfuscation cases (I'll have a think and PR).

**Comment by SymbolixAU** [comment]
I do add a `sfc_columns` attribute to the result of `sf_to_df()`, which contains the column names of the coordinates. So a possibility is to check if that attribute exists and use those columns, else revert to just using `x` & `y`?

**Comment by mdsumner** [comment]
As in, a "leftovers columns" report is probably in order: 

```
message("hey we used x, y, linestring_id, but see you also have multipoint_id, x.., y.. and z - just fyi ...")
```

That also fits into the column matching logic that's a bit ugly right now, I'll make it part of that - got a rough timeline for the next release?

**Comment by mdsumner** [comment]
Oh neat re the attributes, I'll check it out
