### ISSUE TITLE
use Roxygen / Markdown?

### ISSUE THREAD

**Issue by mdsumner** [dcooley/sfheaders#65]
@dcooley can we use Roxygen Markdown? I.e. I put this in DESCRIPTION to support my habits in writing roxygen comments:

```
Roxygen: list(markdown = TRUE)
```
https://roxygen2.r-lib.org/articles/markdown.html

You won't need to use the features - they co-exist, so this is a *style-guide* question :)

(else I will recraft my links and lists and code chunks using trad Rd)

**Comment by dcooley** [comment]
yeah if it doesn't break the existing docs I have no issue with you adding it to your PR.
