### ISSUE TITLE
feature request: add argument `max_area` in nngeo::st_remove_holes()?

### ISSUE THREAD

**Issue by MatthieuStigler** [dcooley/sfheaders#93]
Hi

`nngeo::st_remove_holes()` is a nice function that seems to be much faster than `nngeo::st_remove_holes()`. Unfortunately, the `max_area` argument in nngeo does not seem available in sfheaders? Is that something that could be added you think?

Thanks!

PS: also, the subtle different names between **st**_remove_holes() and **sf**_remove_holes() was quite confusing (even nngeo got it wrong in the current help page)... is it intentional?

**Comment by dcooley** [comment]
Can you give a bit more detail; what does `max_area` do?

**Comment by MatthieuStigler** [comment]
This allows to set a maximum area beyond which holes are not removed. It was particularly useful in a case, where I wanted to clean geometries from small pounds etc, but did not want to remove big lakes. 

Thanks!!

**Comment by dcooley** [comment]
I don't think this is possible in `sfheaders` because it has no 'geospatial' capability (e.g. calculating lengths, distances, areas etc). It's purely for manipulating R objects to and from `sf` structures.

**Comment by mdsumner** [comment]
fwiw, the data frame representation is a good place to do such a cull, though - I'm interested to have a look, I have easily run code to calculate areas in this df form - it's long been a happy place for me, the "tidy" representation of complex formats exactly to enable basic geom operations without being held ransom to bespoke formats and their ideologies ;)

**Comment by mdsumner** [comment]
ok so, using [hypertidy/area](https://github.com/hypertidy/area) - I haven't checked the actual calcs in a while, so use with caution

``` r

library(area) ## devtools::install_github("hypertidy/area")
library(sfheaders)
## polygon with lots of holes
sfx <- sf::st_set_crs(silicate::inlandwaters, sf::st_crs(silicate::inlandwaters))

bb <- sf::st_bbox(sfx)
bb["ymin"] <- -2e6
sfx <- sf::st_cast(sf::st_crop(sfx,bb)) ## just zap Macquarie Island for better figures

library(tmap)
tm_shape(sfx) + tm_borders() + tm_facets(by = "Province") + tm_fill("grey")
```

![](https://i.imgur.com/44Z6VgE.png)

``` r
library(dplyr)
## decompose to data frame and calculate area for every ring (every nested linestring_id)
df <- sf_to_df(sfx) %>% 
  group_by(g = multipolygon_id, polygon_id, linestring_id) %>%  ## note might not have multipolygon_id
  mutate(area = area::polygon_area(cbind(x, y))) %>% ungroup()  ## not signed by default


## keep if 
## 1) isn't  the first linestring in a polygon
## 2) is as big as ACT (ish)
ar <- 2100e6
plot(df  %>% mutate(ok = linestring_id < 2 | area >= ar) %>% filter(ok) %>% sf_mpoly(), col = "grey")
```

![](https://i.imgur.com/vGbWyRA.png)

``` r

df %>% ungroup() %>% mutate(ok = linestring_id < 2 | area >= ar) %>% filter(ok) %>% sf_mpoly() %>% 
  tm_shape() + tm_borders() + tm_facets(by = "multipolygon_id") + tm_fill("firebrick")
```

![](https://i.imgur.com/MWqsg6e.png)

<sup>Created on 2022-05-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dcooley** [comment]
@mdsumner as always shows us the light. But I think this highlights this sort of operation is out-of-scope for {sfheaders}. 

> PS: also, the subtle different names between st_remove_holes() and sf_remove_holes() was quite confusing (even nngeo got it wrong in the current help page)... is it intentional?

yes I deliberately chose **sf_** so it was "clear" these were not functions from the {sf} library, which uses **st_**
