### ISSUE TITLE
github.io docs out of date

### ISSUE THREAD

**Issue by mdsumner** [dcooley/sfheaders#95]
There's no 'sf_cast' for example, and it's listed at version 1.0.0

https://dcooley.github.io/sfheaders/reference/index.html

hosted out of /docs/ still?  run `usethis::use_github_actions("pkgdown")' should be enough :)

**Comment by dcooley** [comment]
thanks for the nudge - now sorted - https://dcooley.github.io/sfheaders/reference/index.html
