### ISSUE TITLE
How to handle limitations to manipulate object in sfc_polygon format?

### ISSUE THREAD

**Issue by karolazvdo** [dcooley/sfheaders#96]
I'm create a hexagonal grid from a shapefile, with 25km² of resolution. I did that with the function st_make_grid, wich return a sfc_polygon object, but now I'm have extrem difficulties to convert this sfc_polygon into a raster (without lose resolution, remaining with 25km² grid size); or even assign a id column to sfc_polygon.

For my purpose, I need to obtain the two formats of this spatial object (the raster and the shapefile). Reading the documentation I didnt find a way to do that, would you help me?

Below I'll let the code that allowed me to create this sfc_polygon.

```r
objeto_shape2 = sf::st_read("C:/Users/Downloads/cerrado_border/cerrado_border.shp") %>%
  slice(1) %>%
  st_geometry() %>%
  st_transform(3857)

cell_area <- 25 * 1000 ^ 2 # target grid size
grid_spacing <- sqrt(2*cell_area/sqrt(3)) # size of hexagon calculated from area

grid <- objeto_shape2 %>% 
  st_make_grid(square = F, cellsize = grid_spacing)
```

**Comment by dcooley** [comment]
Hi @karolazvdo , I don't see any use of `sfheaders`, or how this questions relates to this package, so I don't think this issue belongs here.
